### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by daapp** [40ants/linter#1]
I have error during installing linter using 
`ros install 40ants-asdf-system 40ants-linter`

...
[package 40ants-linter/main].

; file: /home/alex/.roswell/lisp/quicklisp/dists/ultralisp/software/40ants-linter-20230308112721/src/main.lisp
; in: DEFMAIN (MAIN)
;     (DEFMAIN/DEFMAIN:DEFMAIN (40ANTS-LINTER/MAIN:MAIN)
;         ((40ANTS-LINTER/MAIN::VERSION "Show program version and exit." :FLAG T)
;          (40ANTS-LINTER/MAIN::IMPORTS
;           "Check for missing or unused imports of package-inferred systems."
;           :FLAG T)
;          (40ANTS-LINTER/MAIN::SYSTEM
;           "ASDF system (or multiple systems, separated by comma)."))
;       "Show information about Lisp implementation and given systems. Useful when collecting information for bugreports."
;       (40ANTS-LINTER/MAIN::REAL-MAIN 40ANTS-LINTER/MAIN::VERSION
;        40ANTS-LINTER/MAIN::SYSTEM :CHECK-IMPORTS 40ANTS-LINTER/MAIN::IMPORTS))
; 
; caught ERROR:
;   (during macroexpansion of (DEFMAIN (MAIN)
;       ...))
;   The value
;     (MAIN)
;   is not of type
;     SYMBOL
;   when binding SYMBOL

Aborted during step [1/3].
Unhandled UIOP/LISP-BUILD:COMPILE-FILE-ERROR in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                          {1001088073}>:
  COMPILE-FILE-ERROR while
  compiling #<CL-SOURCE-FILE "40ants-linter/main" "lisp">

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001088073}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1003CFA6E3}> #<unused argument> :QUIT T)
1: (SB-DEBUG::RUN-HOOK SB-EXT:*INVOKE-DEBUGGER-HOOK* #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1003CFA6E3}>)
2: (INVOKE-DEBUGGER #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1003CFA6E3}>)
...

**Comment by svetlyak40wt** [comment]
Seems, defmain is too old. Try to update your quickload dist by a call to ql:update-all-dists.

**Comment by daapp** [comment]
> 
CL-USER> (ql-dist:all-dists)
(#<QL-DIST:DIST quicklisp 2023-02-15> #<QL-DIST:DIST ultralisp 20230309010501>)

**Comment by svetlyak40wt** [comment]
This is strange.

What if you'll install these systems one by one? Like this:

```
ros install 40ants-asdf-system
ros install 40ants-linter
```

**Comment by daapp** [comment]
Yes, 40ants-asdf-system already installed, and 40ants-linter unable to install.

**Comment by svetlyak40wt** [comment]
This is strange. I'll try to reproduce this on an empty virtual machine soon.

**Comment by svetlyak40wt** [comment]
I've created an empty Ubuntu machine and installed latest Roswell:

```
sudo apt-get install make bzip2
curl -sOL https://github.com/roswell/roswell/releases/download/v22.12.14.113/roswell_22.12.14.113-1_amd64.deb
sudo dpkg -i roswell_22.12.14.113-1_amd64.deb

$ ros version
roswell 22.12.14.113(NO-GIT-REVISION)
build with gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
libcurl=7.58.0
Quicklisp=2021-02-13
Dist=2023-02-15
lispdir='/etc/roswell/'
homedir='/home/art/.roswell/'
configdir='/home/art/.roswell/'
sbcl-bin-variant=''

$ ros config
setup.time=3887341954
sbcl-bin.version=2.3.2
default.lisp=sbcl-bin
```

Then added the Ultralisp dist to it:

```
> (ql-dist:all-dists)
(#<QL-DIST:DIST quicklisp 2023-02-15> #<QL-DIST:DIST ultralisp 20230309010501>)

> (asdf:asdf-version)
"3.3.1"
```

and command `ros install 40ants-asdf-system 40ants-linter` ended with success.

Something wrong with your environment. Please, provide output of `ros version`, `ros config`, `(asdf:asdf-version)` and `(ql:where-is-system :40ants-asdf-system)`.

**Comment by daapp** [comment]
% ros version
roswell 20.06.14.107(177a646)
build with gcc (Debian 8.3.0-6) 8.3.0
libcurl=7.64.0
Quicklisp=2021-02-13
Dist=2023-02-15
lispdir='/home/alex/.local/etc/roswell/'
homedir='/home/alex/.roswell/'
configdir='/home/alex/.roswell/'

% ros config
default-lisp=sbcl/2.0.6
setup.time=3887295611
ccl-bin.version=1.11.5
sbcl-bin.version=2.3.2
sbcl.version=2.0.6
default.lisp=sbcl-bin

Possible subcommands:
set
show

CL-USER> (asdf:asdf-version)
"3.3.1"

CL-USER> (ql:where-is-system :40ants-asdf-system)
#P"/home/alex/.roswell/lisp/quicklisp/dists/ultralisp/software/40ants-40ants-asdf-system-20230210163819/"

$ cat /etc/devuan_version 
daedalus/ceres

Looks like my roswell/quicklisp broken. I create new system user and it works clean.
